#!/bin/bash
shopt -s extglob
# set -o errexit

function abort {
    if [ $# -gt 0 ]; then
        echo "$*"
    fi
    exit 1
}

function display_help {
    echo "usage: $(basename "$0") script-file [args..]"
}

function abort_and_display_help {
    display_help
    abort "$@"
}

asking_for_help=false
case "$1" in
    --help|-h)
        asking_for_help=true
        ;;
esac

here="$(cd -L "$(dirname "$(readlink "$0" || echo "$0")")";pwd)"

if [ $asking_for_help = true ]; then
    display_help
    exit 0
fi

set -o nounset

## END TEMPLATE

LAUNCHER_CLASSPATH="$HOME/MCP/Projects/clj/clj-1.0.0-SNAPSHOT-standalone.jar"
if [ -z "$LAUNCHER_CLASSPATH" ]
then
    echo "!CHEATING ON THE CLASSPATH!" >&2
    LAUNCHER_CLASSPATH="$(cd "$HOME/MCP/Projects/clj"; lein classpath)"
fi

# while [ $# -gt 0 ]
# do
#     case "$1" in
#         *)
#             break
#             ;;
#     esac
# done

set -o nounset

script="$(cd -L "$(dirname "$(readlink "$1" || echo "$1")")";pwd)/$(basename "$1")"
shift
exec ng net.bstiles.mcp.nail "@/net/bstiles/clj/main.clj" "$script" "$@"









